name: generate snake game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake SVG
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: tturkayy
          outputs: |
            dist/github-contribution-grid-snake.svg?palette=github-dark&color_snake=#3b82f6

      - name: Commit and push SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "chore: update snake contribution game [skip ci]" || exit 0
          git push
